# Generated by Django 4.2.14 on 2024-07-23 09:08

from django.db import migrations, models

import simple_certmanager.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="The common name for the certificate", max_length=100
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        blank=True,
                        default="NL",
                        help_text="Two-letter country code",
                        max_length=2,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the organization",
                        max_length=100,
                    ),
                ),
                (
                    "state_or_province_name",
                    models.CharField(
                        blank=True,
                        help_text="The state or province name",
                        max_length=100,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for the certificate",
                        max_length=254,
                    ),
                ),
                (
                    "csr",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Certificate Signing Request",
                        verbose_name="CSR",
                    ),
                ),
                ("private_key", models.TextField(blank=True, editable=False)),
            ],
            bases=(simple_certmanager.mixins.DeleteFileFieldFilesMixin, models.Model),
        ),
    ]
