# Generated by Django 4.2.14 on 2024-07-22 11:06

import django.db.models.deletion
from django.db import migrations, models

import privates.fields
import privates.storages

import simple_certmanager.mixins
import simple_certmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0002_alter_certificate_private_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_name",
                    models.CharField(
                        blank=True,
                        default="NL",
                        help_text="Two-letter country code",
                        max_length=2,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the organization",
                        max_length=100,
                    ),
                ),
                (
                    "state_or_province_name",
                    models.CharField(
                        blank=True,
                        help_text="The state or province name",
                        max_length=100,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for the certificate",
                        max_length=254,
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        help_text="The common name for the certificate", max_length=100
                    ),
                ),
                (
                    "private_key",
                    privates.fields.PrivateMediaFileField(
                        blank=True,
                        help_text="The content of the private key",
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="ssl_certs_keys/%Y/%m/%d",
                        validators=[
                            simple_certmanager.validators.PrivateKeyValidator()
                        ],
                        verbose_name="private key",
                    ),
                ),
                ("csr", models.TextField(blank=True, editable=False)),
            ],
            bases=(simple_certmanager.mixins.DeleteFileFieldFilesMixin, models.Model),
        ),
        migrations.AddField(
            model_name="certificate",
            name="signing_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate",
                to="simple_certmanager.signingrequest",
            ),
        ),
    ]
