# Generated by Django 6.0.5 on 2026-05-15 20:42

from django.db import migrations

import privates.fields

import simple_certmanager.validators


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0006_remove_signingrequest_csr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="private_key",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The content of the private key",
                upload_to="ssl_certs_keys/%Y/%m/%d",
                validators=[simple_certmanager.validators.PrivateKeyValidator()],
                verbose_name="private key",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="public_certificate",
            field=privates.fields.PrivateMediaFileField(
                help_text="The content of the certificate",
                upload_to="ssl_certs_keys/%Y/%m/%d",
                validators=[simple_certmanager.validators.PublicCertValidator()],
                verbose_name="public certificate",
            ),
        ),
    ]
